PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>
PREFIX wbml: <https://example.org/wbml#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?tm rr:predicateObjectMap ?pomMap .

  ?pomMap rr:predicate skos:altLabel ;
          rr:objectMap ?objectMap .

  ?objectMap rr:template ?template .
  ?objectMap rr:language ?language .
}
WHERE {
  ?tm wbml:aliasMap ?wom .

  ?wom wbml:template ?template .
  OPTIONAL { ?wom wbml:language ?language . }

  BIND(IRI(CONCAT(STR(?tm), "/pom/aliasMap/", ENCODE_FOR_URI(STR(?wom)))) AS ?pomMap)
  BIND(IRI(CONCAT(STR(?pomMap), "/om")) AS ?objectMap)
}
