PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX wbml: <https://example.org/wbml#>

CONSTRUCT {
  ?tm rr:subjectMap ?subjectMap .

  ?subjectMap rr:template ?template ;
              rr:termType rr:IRI ;
              rr:class ?classIRI .
}
WHERE {
  ?tm wbml:itemMap ?sm .
  OPTIONAL { ?sm wbml:nodeTemplate ?nodeTemplate . }
  OPTIONAL { ?sm wbml:nodeId ?nodeId . }
  FILTER(BOUND(?nodeTemplate) || BOUND(?nodeId))

OPTIONAL {
    {
      ?sm wbml:class ?classNode .
      OPTIONAL { ?classNode wbml:nodeTemplate ?classExplicitKey . }
      BIND(COALESCE(?classExplicitKey, STRAFTER(STR(?classNode), "#")) AS ?classKey)
      BIND(IRI(CONCAT("urn:wikibase:item:", ?classKey)) AS ?classIRI)
    }
    UNION
    {
      ?sm wbml:classId ?classIdStr .
      BIND(IRI(CONCAT("urn:wikibase:itemIRI:", STR(?classIdStr))) AS ?classIRI)
    }
  }

  BIND(IRI(CONCAT(STR(?tm), "/subjectMap")) AS ?subjectMap)
  BIND(
    IF(BOUND(?nodeId),
      CONCAT("urn:wikibase:itemIRI:", STR(?nodeId)),
      CONCAT("urn:wikibase:item:", STR(?nodeTemplate))
    ) AS ?template
  )
}
