PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX wbml: <https://example.org/wbml#>

CONSTRUCT {
  ?tm rr:subjectMap ?subjectMap .

  ?subjectMap rr:template ?template ;
              rr:termType rr:IRI ;
              rr:class ?classIRI .
}
WHERE {
  ?tm wbml:subjectMap ?sm .
  ?sm wbml:nodeId ?nodeId ;
      wbml:classKey ?classKey .

  BIND(IRI(CONCAT(STR(?tm), "/subjectMap")) AS ?subjectMap)
  BIND(CONCAT("urn:wikibase:item:", STR(?classKey), "_{", STR(?nodeId), "}") AS ?template)
  BIND(IRI(CONCAT("urn:wikibase:item:", STR(?classKey))) AS ?classIRI)
}
