PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX wbml: <https://example.org/wbml#>

CONSTRUCT {
  ?tm rr:subjectMap ?subjectMap .

  ?subjectMap rr:template ?template ;
              rr:termType rr:IRI .
}
WHERE {
  ?tm wbml:subjectMap ?sm .
  ?sm wbml:nodeId ?nodeId .

  FILTER NOT EXISTS { ?sm wbml:classKey ?anyClass }

  BIND(IRI(CONCAT(STR(?tm), "/subjectMap")) AS ?subjectMap)
  BIND(CONCAT("urn:wikibase:item:{", STR(?nodeId), "}") AS ?template)
}
