PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX wbml: <https://example.org/wbml#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?tm rr:predicateObjectMap ?pomMap .

  ?pomMap rr:predicate rdf:type ;
          rr:objectMap ?objectMap .

  ?objectMap rr:constant ?classIRI .
}
WHERE {
  ?tm wbml:predicateObjectMap ?pom .
  ?pom wbml:predicate rdf:type ;
       wbml:objectMap ?wom .

  ?wom wbml:classKey ?classKey .

  BIND(IRI(CONCAT(STR(?tm), "/pom/type/", ENCODE_FOR_URI(STR(?wom)))) AS ?pomMap)
  BIND(IRI(CONCAT(STR(?pomMap), "/om")) AS ?objectMap)
  BIND(IRI(CONCAT("urn:wikibase:item:", STR(?classKey))) AS ?classIRI)
}
