PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX wbml: <https://example.org/wbml#>
PREFIX wbint: <https://example.org/wbint#>

CONSTRUCT {
  ?stmtTM a rr:TriplesMap ;
          rml:logicalSource ?ls ;
          rr:subjectMap ?stmtSM ;
          rr:predicateObjectMap ?subjectPOM ;
          rr:predicateObjectMap ?propertyPOM ;
          rr:predicateObjectMap ?valuePOM .

  ?stmtSM rr:template ?stmtTemplate ;
          rr:termType rr:IRI .

  ?subjectPOM rr:predicate wbml:statementSubject ;
              rr:objectMap ?subjectOM .

  ?subjectOM rr:template ?subjectTemplate ;
             rr:termType rr:IRI .

  ?propertyPOM rr:predicate wbml:statementProperty ;
               rr:objectMap ?propertyOM .

  ?propertyOM rr:constant ?propIRI .

  ?valuePOM rr:predicate wbml:statementValue ;
            rr:objectMap ?valueOM .

  ?valueOM rml:reference ?reference .
  ?valueOM rr:datatype ?datatype .
  ?valueOM rr:language ?language .
}
WHERE {
  ?tm a rr:TriplesMap ;
      rml:logicalSource ?ls ;
      wbml:itemMap ?sm ;
      wbml:statementMap ?pom .

  ?sm wbml:nodeTemplate ?subjectNodeTemplate .

  ?pom wbint:statID ?statID ;
       wbml:valueMap ?wom .

  OPTIONAL { ?pom wbml:propertyMap ?propertyNode . }
  OPTIONAL { ?pom wbml:propertyId ?propertyIdStr . }
  FILTER(BOUND(?propertyNode) || BOUND(?propertyIdStr))

  ?wom wbml:reference ?reference .
  OPTIONAL { ?wom wbml:datatype ?datatype . }
  OPTIONAL { ?wom wbml:language ?language . }
  OPTIONAL { ?propertyNode wbml:nodeTemplate ?propExplicitKey . }

  FILTER(!BOUND(?propertyNode) || ?propertyNode NOT IN (rdfs:label, rdfs:comment, skos:altLabel))

  BIND(IRI(CONCAT(STR(?tm), "/statement/", STR(?statID))) AS ?stmtTM)
  BIND(IRI(CONCAT(STR(?stmtTM), "/subjectMap")) AS ?stmtSM)

  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/subject")) AS ?subjectPOM)
  BIND(IRI(CONCAT(STR(?subjectPOM), "/om")) AS ?subjectOM)

  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/property")) AS ?propertyPOM)
  BIND(IRI(CONCAT(STR(?propertyPOM), "/om")) AS ?propertyOM)

  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/value/", ENCODE_FOR_URI(STR(?wom)))) AS ?valuePOM)
  BIND(IRI(CONCAT(STR(?valuePOM), "/om")) AS ?valueOM)

  BIND(
    IF(BOUND(?propertyIdStr),
      IRI(CONCAT("urn:wikibase:propertyIRI:", STR(?propertyIdStr))),
      COALESCE(
        IRI(CONCAT("urn:wikibase:property:", ?propExplicitKey)),
        IF(
          STRSTARTS(STR(?propertyNode), "https://example.org/wbml#"),
          IRI(CONCAT("urn:wikibase:property:", STRAFTER(STR(?propertyNode), "#"))),
          ?propertyNode
        )
      )
    ) AS ?propIRI
  )

  BIND(
    CONCAT("urn:wikibase:item:", STR(?subjectNodeTemplate)) AS ?subjectTemplate
  )

  BIND(
    CONCAT("urn:wikibase:statement:", STR(?subjectNodeTemplate), "_", STR(?statID), "_{", STR(?reference), "}") AS ?stmtTemplate
  )
}
