PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>
PREFIX wbml: <https://example.org/wbml#>

CONSTRUCT {
  ?stmtTM a rr:TriplesMap ;
          rml:logicalSource ?ls ;
          rr:subjectMap ?stmtSM ;
          rr:predicateObjectMap ?rankPOM .

  ?stmtSM rr:template ?stmtTemplate ;
          rr:termType rr:IRI .

  ?rankPOM rr:predicate wbml:rank ;
           rr:objectMap ?rankOM .

  ?rankOM rr:constant ?rankIRI .
}
WHERE {
  ?tm a rr:TriplesMap ;
      rml:logicalSource ?ls ;
      wbml:subjectMap ?sm ;
      wbml:predicateObjectMap ?pom .

  ?sm wbml:nodeTemplate ?subjectNodeTemplate .

  ?pom wbml:predicate ?predicateNode ;
       wbml:statID ?statID ;
       wbml:objectMap ?wom ;
       wbml:rank ?rankIRI .

  OPTIONAL { ?wom wbml:reference ?mainReference . }
  OPTIONAL { ?wom wbml:nodeTemplate ?mainValueNodeTemplate . }
  OPTIONAL { ?wom wbml:joinCondition / wbml:child ?childKey . }

  FILTER(?predicateNode NOT IN (rdfs:label, rdfs:comment, skos:altLabel))

  BIND(IRI(CONCAT(STR(?tm), "/statement/", STR(?statID))) AS ?stmtTM)

  BIND(
    IF(BOUND(?mainReference),       CONCAT("_{", STR(?mainReference), "}"),
    IF(BOUND(?mainValueNodeTemplate), CONCAT("_", STR(?mainValueNodeTemplate)),
    IF(BOUND(?childKey),            CONCAT("_{", STR(?childKey), "}"),
    "")))
  AS ?valueSuffix)

  BIND(
    CONCAT(
      "urn:wikibase:statement:", STR(?subjectNodeTemplate), "_", STR(?statID), ?valueSuffix
    )
    AS ?stmtTemplate
  )

  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/rank")) AS ?rankPOM)
  BIND(IRI(CONCAT(STR(?rankPOM), "/om")) AS ?rankOM)
}
