PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>

PREFIX wbml: <https://example.org/wbml#>
PREFIX wbint: <https://example.org/wbint#>

CONSTRUCT {
  ?stmtTM a rr:TriplesMap ;
          rml:logicalSource ?ls ;
          rr:subjectMap ?stmtSM ;
          rr:predicateObjectMap ?qualifierPOM .

  ?stmtSM rr:template ?stmtTemplate ;
          rr:termType rr:IRI .

  ?qualifierPOM rr:predicate ?qualifierPropIRI ;
                rr:objectMap ?qualifierOM .

  ?qualifierOM rml:reference ?reference .
  ?qualifierOM rr:datatype ?datatype .
  ?qualifierOM rr:language ?language .
}
WHERE {
  ?tm a rr:TriplesMap ;
      rml:logicalSource ?ls ;
      wbml:statementMap ?pom ;
      wbml:entityMap ?sm .

  OPTIONAL { ?sm wbml:entityTemplate ?subjectEntityTemplate . }
  OPTIONAL { ?sm wbml:entityId ?subjectEntityId . }
  FILTER(BOUND(?subjectEntityTemplate) || BOUND(?subjectEntityId))
  BIND(COALESCE(?subjectEntityTemplate, ?subjectEntityId) AS ?subjectKey)

  ?pom wbint:statID ?statID ;
       wbml:valueMap ?wom ;
       wbml:qualifierMap ?qmap .

  OPTIONAL { ?wom wbml:reference ?mainReference . }
  OPTIONAL { ?wom wbml:entityTemplate ?mainValueEntityTemplate . }
  OPTIONAL { ?wom wbml:entityId ?mainValueEntityId . }
  OPTIONAL { ?wom wbml:joinCondition / wbml:child ?childKey . }
  OPTIONAL { ?wom wbml:template ?mainValueTemplate . }

  BIND(COALESCE(?mainValueEntityTemplate, ?mainValueEntityId) AS ?mainValueNode)

  ?qmap wbml:valueMap ?qom .

  OPTIONAL { ?qmap wbml:propertyMap ?qualifierPropertyNode . }
  OPTIONAL { ?qmap wbml:propertyId ?qualifierPropertyId . }
  FILTER(BOUND(?qualifierPropertyNode) || BOUND(?qualifierPropertyId))

  OPTIONAL { ?qualifierPropertyNode wbml:entityTemplate ?qualExplicitKey . }
  FILTER(
    !BOUND(?qualifierPropertyNode) ||
    isBlank(?qualifierPropertyNode) ||
    STRSTARTS(STR(?qualifierPropertyNode), "https://example.org/wbml#")
  )

  ?qom wbml:reference ?reference .
  OPTIONAL { ?qom wbml:datatype ?datatype . }
  OPTIONAL { ?qom wbml:language ?language . }

  BIND(IRI(CONCAT(STR(?tm), "/statement/", STR(?statID))) AS ?stmtTM)
  BIND(IRI(CONCAT(STR(?stmtTM), "/subjectMap")) AS ?stmtSM)

  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/qualifier/", ENCODE_FOR_URI(STR(?qmap)))) AS ?qualifierPOM)
  BIND(IRI(CONCAT(STR(?qualifierPOM), "/om")) AS ?qualifierOM)

  BIND(
    IF(BOUND(?mainReference),       CONCAT("_{", STR(?mainReference), "}"),
    IF(BOUND(?mainValueNode), CONCAT("_", STR(?mainValueNode)),
    IF(BOUND(?childKey),            CONCAT("_{", STR(?childKey), "}"),
    IF(BOUND(?mainValueTemplate), CONCAT("_", STR(?mainValueTemplate)),
     ""))))
  AS ?valueSuffix)

  BIND(
    CONCAT(
      "urn:wikibase:statement:", STR(?subjectKey), "_", STR(?statID), ?valueSuffix
    )
    AS ?stmtTemplate
  )

  BIND(
    IF(BOUND(?qualifierPropertyId),
      IRI(CONCAT("urn:wikibase:qualifierIRI:", STR(?qualifierPropertyId))),
      COALESCE(
        IRI(CONCAT("urn:wikibase:qualifier:", ?qualExplicitKey)),
        IRI(CONCAT("urn:wikibase:qualifier:", STRAFTER(STR(?qualifierPropertyNode), "#")))
      )
    ) AS ?qualifierPropIRI
  )
}
