PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>

PREFIX wbml: <https://example.org/wbml#>
PREFIX wbint: <https://example.org/wbint#>

CONSTRUCT {
  ?stmtTM a rr:TriplesMap ;
          rml:logicalSource ?ls ;
          rr:subjectMap ?stmtSM ;
          rr:predicateObjectMap ?qualifierPOM .

  ?stmtSM rr:template ?stmtTemplate ;
          rr:termType rr:IRI .

  ?qualifierPOM rr:predicate ?qualifierPropIRI ;
                rr:objectMap ?qualifierOM .

  ?qualifierOM rr:template ?valueTemplate ;
               rr:termType rr:IRI .
}
WHERE {
  ?tm a rr:TriplesMap ;
      rml:logicalSource ?ls ;
      wbml:itemMap ?sm ;
      wbml:predicateObjectMap ?pom .

  ?sm wbml:nodeTemplate ?subjectNodeTemplate .

  ?pom wbint:statID ?statID ;
       wbml:valueMap ?wom ;
       wbml:qualifierMap ?qmap .

  OPTIONAL { ?wom wbml:reference ?mainReference . }
  OPTIONAL { ?wom wbml:nodeTemplate ?mainValueNodeTemplate . }
  OPTIONAL { ?wom wbml:nodeId ?mainValueNodeId . }
  OPTIONAL { ?wom wbml:joinCondition / wbml:child ?childKey . }

  BIND(COALESCE(?mainValueNodeTemplate, ?mainValueNodeId) AS ?mainValueNode)

  ?qmap wbml:valueMap ?qom .

  OPTIONAL { ?qmap wbml:propertyMap ?qualifierPropertyNode . }
  OPTIONAL { ?qmap wbml:propertyId ?qualifierPropertyId . }
  FILTER(BOUND(?qualifierPropertyNode) || BOUND(?qualifierPropertyId))

  OPTIONAL { ?qualifierPropertyNode wbml:nodeTemplate ?qualExplicitKey . }
  FILTER(
    !BOUND(?qualifierPropertyNode) ||
    isBlank(?qualifierPropertyNode) ||
    STRSTARTS(STR(?qualifierPropertyNode), "https://example.org/wbml#")
  )

  OPTIONAL { ?qom wbml:nodeTemplate ?valueNodeTemplate . }
  OPTIONAL { ?qom wbml:nodeId ?valueNodeId . }
  FILTER(
    (BOUND(?valueNodeTemplate) && CONTAINS(STR(?valueNodeTemplate), "{")) ||
    (BOUND(?valueNodeId)       && CONTAINS(STR(?valueNodeId), "{"))
  )

  BIND(IRI(CONCAT(STR(?tm), "/statement/", STR(?statID))) AS ?stmtTM)
  BIND(IRI(CONCAT(STR(?stmtTM), "/subjectMap")) AS ?stmtSM)
  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/qualifier/", ENCODE_FOR_URI(STR(?qmap)))) AS ?qualifierPOM)
  BIND(IRI(CONCAT(STR(?qualifierPOM), "/om")) AS ?qualifierOM)

  BIND(
    IF(BOUND(?mainReference),       CONCAT("_{", STR(?mainReference), "}"),
    IF(BOUND(?mainValueNode), CONCAT("_", STR(?mainValueNode)),
    IF(BOUND(?childKey),            CONCAT("_{", STR(?childKey), "}"),
    "")))
  AS ?valueSuffix)

  BIND(
    CONCAT(
      "urn:wikibase:statement:", STR(?subjectNodeTemplate), "_", STR(?statID), ?valueSuffix
    )
    AS ?stmtTemplate
  )

  BIND(
    IF(BOUND(?valueNodeId),
      CONCAT("urn:wikibase:itemIRI:", STR(?valueNodeId)),
      CONCAT("urn:wikibase:item:",    STR(?valueNodeTemplate))
    ) AS ?valueTemplate
  )

  BIND(
    IF(BOUND(?qualifierPropertyId),
      IRI(CONCAT("urn:wikibase:qualifierIRI:", STR(?qualifierPropertyId))),
      COALESCE(
        IRI(CONCAT("urn:wikibase:qualifier:", ?qualExplicitKey)),
        IRI(CONCAT("urn:wikibase:qualifier:", STRAFTER(STR(?qualifierPropertyNode), "#")))
      )
    ) AS ?qualifierPropIRI
  )
}
