PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>
PREFIX wbml: <https://example.org/wbml#>

CONSTRUCT {
  ?stmtTM a rr:TriplesMap ;
          rml:logicalSource ?ls ;
          rr:subjectMap ?stmtSM ;
          rr:predicateObjectMap ?referencePOM .

  ?stmtSM rr:template ?stmtTemplate ;
          rr:termType rr:IRI .

  ?referencePOM rr:predicate wbml:statementReference ;
                rr:objectMap ?referenceOM .

  ?referenceOM rr:template ?stmtRefTemplate ;
               rr:termType rr:IRI .
}
WHERE {
  ?tm a rr:TriplesMap ;
      rml:logicalSource ?ls ;
      wbml:subjectMap ?sm ;
      wbml:predicateObjectMap ?pom .

  ?sm wbml:nodeId ?subjectNodeId .
  OPTIONAL { ?sm wbml:classKey ?subjectClassKey . }

  ?pom wbml:statID ?statID ;
       wbml:referenceMap ?rmap .

  ?rmap wbml:refId ?refId .

  BIND(IRI(CONCAT(STR(?tm), "/statement/", STR(?statID))) AS ?stmtTM)
  BIND(IRI(CONCAT(STR(?stmtTM), "/subjectMap")) AS ?stmtSM)
  BIND(IRI(CONCAT(STR(?stmtTM), "/pom/reference/", STR(?refId))) AS ?referencePOM)
  BIND(IRI(CONCAT(STR(?referencePOM), "/om")) AS ?referenceOM)

  BIND(
    IF(
      BOUND(?subjectClassKey),
      CONCAT(
        "urn:wikibase:statement:",
        STR(?subjectClassKey), "_{", STR(?subjectNodeId), "}_", STR(?statID)
      ),
      CONCAT(
        "urn:wikibase:statement:{", STR(?subjectNodeId), "}_", STR(?statID)
      )
    ) AS ?stmtTemplate
  )

  BIND(
    IF(
      BOUND(?subjectClassKey),
      CONCAT(
        "urn:wikibase:statementreference:",
        STR(?subjectClassKey), "_{", STR(?subjectNodeId), "}_", STR(?statID), "_", STR(?refId)
      ),
      CONCAT(
        "urn:wikibase:statementreference:{", STR(?subjectNodeId), "}_", STR(?statID), "_", STR(?refId)
      )
    ) AS ?stmtRefTemplate
  )
}
