PREFIX rr:   <http://www.w3.org/ns/r2rml#>
PREFIX rml:  <http://semweb.mmlab.be/ns/rml#>
PREFIX wbml: <https://example.org/wbml#>

CONSTRUCT {
  ?refTM a rr:TriplesMap ;
         rml:logicalSource ?ls ;
         rr:subjectMap ?refSM ;
         rr:predicateObjectMap ?recordPOM .

  ?refSM rr:template ?stmtRefTemplate ;
         rr:termType rr:IRI .

  ?recordPOM rr:predicate ?refPredIRI ;
             rr:objectMap ?recordOM .

  ?recordOM rr:constant ?constant .
  ?recordOM rr:datatype ?datatype .
  ?recordOM rr:language ?language .
}
WHERE {
  ?tm a rr:TriplesMap ;
      rml:logicalSource ?ls ;
      wbml:subjectMap ?sm ;
      wbml:predicateObjectMap ?pom .

  ?sm wbml:nodeTemplate ?subjectNodeTemplate .

  ?pom wbml:statID ?statID ;
       wbml:objectMap ?wom ;
       wbml:referenceMap ?rmap .

  OPTIONAL { ?wom wbml:reference ?mainReference . }
  OPTIONAL { ?wom wbml:nodeTemplate ?mainValueNodeTemplate . }
  OPTIONAL { ?wom wbml:joinCondition / wbml:child ?childKey . }

  ?rmap wbml:refId ?refId ;
        wbml:referenceRecord ?rrec .

  ?rrec wbml:predicateKey ?refPredicateKey ;
        wbml:objectMap ?rom .

  ?rom wbml:constant ?constant .
  OPTIONAL { ?rom wbml:datatype ?datatype . }
  OPTIONAL { ?rom wbml:language ?language . }

  BIND(IRI(CONCAT(STR(?tm), "/statement/", STR(?statID), "/reference/", STR(?refId))) AS ?refTM)
  BIND(IRI(CONCAT(STR(?refTM), "/subjectMap")) AS ?refSM)
  BIND(IRI(CONCAT(STR(?refTM), "/pom/referenceRecord/", ENCODE_FOR_URI(STR(?rrec)))) AS ?recordPOM)
  BIND(IRI(CONCAT(STR(?recordPOM), "/om")) AS ?recordOM)

  BIND(IRI(CONCAT("urn:wikibase:reference:", STR(?refPredicateKey))) AS ?refPredIRI)

  BIND(
    IF(BOUND(?mainReference),       CONCAT("_{", STR(?mainReference), "}"),
    IF(BOUND(?mainValueNodeTemplate), CONCAT("_", STR(?mainValueNodeTemplate)),
    IF(BOUND(?childKey),            CONCAT("_{", STR(?childKey), "}"),
    "")))
  AS ?valueSuffix)

  BIND(
    CONCAT(
      "urn:wikibase:statementreference:", STR(?subjectNodeTemplate), "_", STR(?statID),
      ?valueSuffix, "_", STR(?refId)
    )
    AS ?stmtRefTemplate
  )
}
