PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wbml: <http://w3id.org/dre/wbml#>

CONSTRUCT {
  ?classIRI a rdfs:Class ;
            rdfs:label    ?classLabel ;
            rdfs:comment  ?classDescription ;
            skos:altLabel ?classAlias ;
            rdfs:subClassOf ?parentClassIRI .
}
WHERE {
  {
    { ?classNode a wbml:Class . }
    UNION
    { [] wbml:class ?classNode . }
  }

  OPTIONAL { ?classNode wbml:label       ?classLabel . }
  OPTIONAL { ?classNode wbml:description ?classDescription . }
  OPTIONAL { ?classNode wbml:alias       ?classAlias . }
  OPTIONAL { ?classNode wbml:entityTemplate      ?classExplicitKey . }

  BIND(COALESCE(?classExplicitKey, STRAFTER(STR(?classNode), "#")) AS ?classKey)
  BIND(IRI(CONCAT("urn:wikibase:item:", ?classKey)) AS ?classIRI)

  OPTIONAL {
    ?classNode wbml:subclassOf ?parentClassNode .
    OPTIONAL { ?parentClassNode wbml:entityTemplate ?parentExplicitKey . }
    BIND(COALESCE(?parentExplicitKey, STRAFTER(STR(?parentClassNode), "#")) AS ?parentKey)
    BIND(IRI(CONCAT("urn:wikibase:item:", ?parentKey)) AS ?parentClassIRI)
  }
}
