PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wbml: <http://w3id.org/dre/wbml#>

CONSTRUCT {
  ?propIRI a rdf:Property ;
           rdfs:label    ?predicateLabel ;
           rdfs:comment  ?predicateDescription ;
           skos:altLabel ?predicateAlias ;
           wbml:propertyType ?predicateType .
}
WHERE {
  {
    { ?propNode a wbml:Property . }
    UNION
    { ?propNode wbml:propertyType ?inferredType .
      FILTER NOT EXISTS { ?propNode a wbml:Property } }
  }

  FILTER NOT EXISTS {
    ?propNode wbml:entityTemplate ?dynTemplate .
    FILTER(CONTAINS(STR(?dynTemplate), "{"))
  }

  OPTIONAL { ?propNode wbml:label       ?predicateLabel . }
  OPTIONAL { ?propNode wbml:description ?predicateDescription . }
  OPTIONAL { ?propNode wbml:alias       ?predicateAlias . }
  OPTIONAL { ?propNode wbml:propertyType      ?predicateType . }
  OPTIONAL { ?propNode wbml:entityTemplate      ?propExplicitKey .
             FILTER(!CONTAINS(STR(?propExplicitKey), "{")) }

  BIND(
    COALESCE(
      IRI(CONCAT("urn:wikibase:property:", ?propExplicitKey)),
      IRI(CONCAT("urn:wikibase:property:", STRAFTER(STR(?propNode), "#")))
    ) AS ?propIRI
  )
}
