CONSTRUCT {
  ?propIRI a wbml:Property ;
           wbml:entityLabel       ?predicateLabel ;
           wbml:entityDescription ?predicateDescription ;
           wbml:entityAlias       ?predicateAlias ;
           wbml:propertyType      ?predicateType .
}
WHERE {
  {
    { ?propNode a wbml:Property . }
    UNION
    { ?propNode wbml:propertyType ?inferredType .
      FILTER NOT EXISTS { ?propNode a wbml:Property } }
  }

  OPTIONAL { ?propNode wbml:entityLabel       ?predicateLabel . }
  OPTIONAL { ?propNode wbml:entityDescription ?predicateDescription . }
  OPTIONAL { ?propNode wbml:entityAlias       ?predicateAlias . }
  OPTIONAL { ?propNode wbml:propertyType      ?predicateType . }
  OPTIONAL { ?propNode wbml:entityTemplate      ?propExplicitKey .
             FILTER(!CONTAINS(STR(?propExplicitKey), "{")) }

  BIND(
    COALESCE(
      IRI(CONCAT("urn:wikibase:property:", ?propExplicitKey)),
      IRI(CONCAT("urn:wikibase:property:", STRAFTER(STR(?propNode), "#")))
    ) AS ?propIRI
  )
}
