PREFIX wbml: <https://example.org/wbml#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?propIRI a rdf:Property ;
           rdfs:label       ?predicateLabel ;
           rdfs:comment     ?predicateDescription ;
           skos:altLabel    ?predicateAlias ;
           wbml:propertyType ?predicateType .
}
WHERE {
  ?propNode a rdf:Property .

  OPTIONAL { ?propNode rdfs:label        ?predicateLabel . }
  OPTIONAL { ?propNode rdfs:comment      ?predicateDescription . }
  OPTIONAL { ?propNode wbml:propertyType ?predicateType . }
  OPTIONAL { ?propNode skos:altLabel     ?predicateAlias . }
  OPTIONAL { ?propNode wbml:nodeTemplate ?propBlankKey . }

  BIND(
    IF(isBlank(?propNode),
       IRI(CONCAT("urn:wikibase:property:", ?propBlankKey)),
       IRI(CONCAT("urn:wikibase:property:", STRAFTER(STR(?propNode), "#")))
    ) AS ?propIRI
  )
}
